# This Script can install an Apache web server for testing and demonstration purposes  
# Author: Lily Pouliot
# Pulled from Ansible Galaxy | allanroque
# Champlain College
# 10 April, 2024

- name: latest Apache version installed
  yum:
    name: httpd
    state: latest

- name: Ensure proper Apache configuration
  copy:
    src: logo-rh-ansible-automation.png
    dest: /var/www/html/logo-rh-ansible-automation.png

- name: deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache

- name: Apache enabled and running
  service:
    name: httpd
    enabled: true
    state: started

- name: Test page link
  uri:
    url: "http://{{ ansible_fqdn}}"
    return_content: no
    status_code: 200
  register: result

- name: Fail if return code is not 200
  fail:
    msg: "HTTP return code is not 200"
  when: result.status != 200

- name: Access page
  debug:
    msg: "http://{{ ansible_fqdn}}"

- name: Updating the Firewall Ports
  hosts: targets
  become: yes
  
  tasks: 
    - name: Add 80/tcp to Firewall
      firewalld: 
        port: 80/tcp
        permanent: yes
        state: enabled
    
