# Ansible playbook to install GitLab
# Savannah Ciak
# April 2024

- name: Install GitLab
  hosts: util01-row
  become: yes

  tasks:
    - name: Install GitLab Dependencies
      yum:
        name: ['curl', 'openssh-server, 'postfix']

    - name: Install GitLab Package Repository
      yum_repository:
        name: 'gitlab'
        description: 'GitLab Community Edition'
        baseurl: 'https://packages.gitlab.com/gitlab/gitlab-ce/el/7/$basearch'
        gpgkey: 'https://packages.gitlab.com/gpg.key'
        enabled: yes
        gpgcheck: yes

    - name: Install GitLab Woot Woot
      yum: 
        name: 'gitlab-ce'
        state: present

   - name: Open port 80
     firewalld:
       service: http
       state: enabled
       permanent: yes
       immediate: yes

  - name: Open port 443
    firewalld: 
      service: https
      state: enabled
      permanent: yes
      immediate: yes

  - name: Reload firewall
    command: firewall-cmd --reload 
       
