# Ansible playbook to create a new windows domain user 
# Resource in the examples of: 
# https://docs.ansible.com/ansible/latest/collections/microsoft/ad/user_module.html#ansible-collections-microsoft-ad-user-module
# Author Savannah Ciak
# 17 April 2024

# May Need to install module using `ansible-galaxy collection install microsoft.ad`

- name: Create New Windows Domain User
  hosts: dc01-row

  tasks:
    - name: Create new user 
      microsoft.ad.user:
        identity: bob
        Firstname: bob
        password: BobPassword01!
        path: ou="Ansible_Users",dc=backrow,dc=local
        enabled: yes
        state: present
        domain_username: Insert your domain username 
        domain_password: Insert your domain password 
        domain_server: dc01-row.backrow.local
        
    - name: Check new user account status
      microsoft.ad.user:
        identity: bob
        path: ou="Ansible_Users",dc=backrow,dc=local
        state: present
